// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "OI.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/DriveWithJoysticks.h"
#include "Commands/FrontArmDown.h"
#include "Commands/FrontArmUp.h"
#include "Commands/RearArmDown.h"
#include "Commands/RearArmUp.h"
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	leftJoystick = new Joystick(1);
	
	btnRearArmUp = new JoystickButton(leftJoystick, 5);
	btnRearArmUp->WhileHeld(new FrontArmUp());
	btnRearArmDown = new JoystickButton(leftJoystick, 6);
	btnRearArmDown->WhileHeld(new RearArmDown());
	rightJoystick = new Joystick(2);
	
	btnFrontArmDown = new JoystickButton(rightJoystick, 6);
	btnFrontArmDown->WhileHeld(new FrontArmDown());
	btnFrontArmUp = new JoystickButton(rightJoystick, 5);
	btnFrontArmUp->WhileHeld(new FrontArmUp());
     
        // SmartDashboard Buttons
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
Joystick* OI::getLeftJoystick() {
	return leftJoystick;
}
Joystick* OI::getRightJoystick() {
	return rightJoystick;
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
