// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
SpeedController* RobotMap::driveTrainLeftMotor = NULL;
SpeedController* RobotMap::driveTrainRightMotor = NULL;
RobotDrive* RobotMap::driveTrainRobotDrive = NULL;
SpeedController* RobotMap::armArmMotor = NULL;
SpeedController* RobotMap::dumpPanDumpMotor = NULL;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();
	driveTrainLeftMotor = new Jaguar(1, 1);
	lw->AddActuator("DriveTrain", "LeftMotor", (Jaguar*) driveTrainLeftMotor);
	
	driveTrainRightMotor = new Jaguar(1, 2);
	lw->AddActuator("DriveTrain", "RightMotor", (Jaguar*) driveTrainRightMotor);
	
	driveTrainRobotDrive = new RobotDrive(driveTrainLeftMotor, driveTrainRightMotor);
	
	driveTrainRobotDrive->SetSafetyEnabled(false);
        driveTrainRobotDrive->SetExpiration(0.1);
        driveTrainRobotDrive->SetSensitivity(0.5);
        driveTrainRobotDrive->SetMaxOutput(1.0);
        
	armArmMotor = new Jaguar(1, 3);
	lw->AddActuator("Arm", "ArmMotor", (Jaguar*) armArmMotor);
	
	dumpPanDumpMotor = new Jaguar(1, 4);
	lw->AddActuator("DumpPan", "DumpMotor", (Jaguar*) dumpPanDumpMotor);
	
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
